/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.40
 * Generated at: 2020-12-05 18:53:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class companyregistration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Register for Company</title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS\\regform.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS\\navstyles.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS\\companylink.css\" />\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Exo+2:wght@300&family=Philosopher:wght@700&display=swap\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <script src=\"JS\\Student\\registrationvalidation.js\" type=\"text/javascript\"></script> \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"navigationbar\" class=\"sticky-top\">\r\n");
      out.write("        <header class=\"row \">\r\n");
      out.write("            <div class=\"col-md-4 col-sm-12 my-auto\">\r\n");
      out.write("                <img src=\"Images\\amritalogo.png\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 col-sm-12 my-auto\">\r\n");
      out.write("                <h1>Student Portal</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 col-sm-12 my-auto\">\r\n");
      out.write("                <button type=\"button\" class=\"btn\" id=\"signinout\" value=\"logout\" name=\"signinout\">Logout</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <nav class=\"nav nav-pills nav-justified\">\r\n");
      out.write("            <a href=\"http://localhost:8080/mainpage.jsp\" class=\"nav-item nav-link\" target=\"mainframe\" id=\"home\" name=\"home\">Home</a>\r\n");
      out.write("            <a href=\"http://localhost:8080/companies_list.jsp\" class=\"nav-item nav-link\" id=\"companies\" name=\"companies\">Companies</a>\r\n");
      out.write("            <a href=\"http://localhost:8080/companyregistration.jsp\" class=\"nav-item nav-link disabled\" id=\"register\" name=\"register\">Registration</a>\r\n");
      out.write("            <a href=\"http://localhost:8080/calendar.jsp\" class=\"nav-item nav-link\" id=\"calendar\" name=\"calendar\">Calendar</a>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"c_registration_pagebody\">\r\n");
      out.write("        <div id=\"selection\" class=\"row align-items-center justify-content-center\">\r\n");
      out.write("            <select name=\"company_name\" onchange=\"populate(this)\">\r\n");
      out.write("                <option value=\"---\" selected>---</option>\r\n");
      out.write("                <option value=\"Mr.Cooper\">Mr.Cooper</option>\r\n");
      out.write("                <option value=\"Amazon\">Amazon</option>\r\n");
      out.write("                <option value=\"Microsoft\">Microsoft</option>\r\n");
      out.write("            </select>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row align-items-center justify-content-center\">\r\n");
      out.write("            <form id=\"register_form\" method=\"POST\" action=\"http://localhost:8080/mainpage.jsp\" onsubmit=\"return validate()\">\r\n");
      out.write("                <h1>Registration Form</h1>\r\n");
      out.write("\r\n");
      out.write("                <fieldset name=\"Personal\" class=\"border-light pl-2 m-3\">\r\n");
      out.write("                    <legend>Personal Details:</legend>\r\n");
      out.write("\r\n");
      out.write("                    <section id=\"name\" class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <label for=\"fname\">First Name</label><br />\r\n");
      out.write("                            <input type=\"text\" name=\"fname\" id=\"fname\" required />\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <label for=\"mname\">Middle Name</label><br />\r\n");
      out.write("                            <input type=\"text\" name=\"mname\" id=\"mname\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4 \">\r\n");
      out.write("                            <label for=\"lname\">Last Name</label><br />\r\n");
      out.write("                            <input type=\"text\" name=\"lname\" id=\"lname\" required />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                    <div id=\"rollnum\" class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <label for=\"rollnum\">Roll Number</label><br />\r\n");
      out.write("                            <input type=\"text\" name=\"rollnum\" id=\"rollnumber\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <section id=\"contact\" class=\"row justify-content-between\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-md-4 col-sm-12\">\r\n");
      out.write("                            <label for=\"email\">EMail ID</label><br />\r\n");
      out.write("                            <input type=\"email\" name=\"email\" id=\"email\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <label for=\"phonenum\">Phone Number</label><br />\r\n");
      out.write("                            <input type=\"number\" name=\"phonenum\" id=\"phonenum\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                    <section id=\"location\" class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <label for=\"address\">Address</label><br />\r\n");
      out.write("                            <textarea name=\"address\" id=\"address\" required></textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                </fieldset>\r\n");
      out.write("\r\n");
      out.write("                <fieldset name=\"Academic\" class=\"border-light pl-2 m-3\">\r\n");
      out.write("                    <legend>Academic Details</legend>\r\n");
      out.write("                    <section id=\"degree-details\" class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <label>Degree</label><br />\r\n");
      out.write("\r\n");
      out.write("                            <label for=\"btech\">B.Tech.</label>\r\n");
      out.write("                            <input type=\"radio\" id=\"btech\" name=\"degree\" value=\"btech\" required>\r\n");
      out.write("\r\n");
      out.write("                            <label for=\"mtech\">M.Tech.</label>\r\n");
      out.write("                            <input type=\"radio\" id=\"mtech\" name=\"degree\" value=\"mtech\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <label for=\"department\">Department</label><br />\r\n");
      out.write("                            <select name=\"department\" id=\"department\" required>\r\n");
      out.write("                                <option value=\"cse\">Computer Science and Engineering</option>\r\n");
      out.write("                                <option value=\"eee\">Electronic and Electrical Engineering</option>\r\n");
      out.write("                                <option value=\"che\">Chemical Engineering</option>\r\n");
      out.write("                                <option value=\"civ\">Civil Engineering</option>\r\n");
      out.write("                                <option value=\"mee\">Mechanical Engineering</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <label for=\"gradyear\">Year of Graduation</label><br />\r\n");
      out.write("                            <input type=\"number\" id=\"gradyear\" name=\"gradyear\" min=2021 max=2023 required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </section>\r\n");
      out.write("                    <section id=\"markdetails\" class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <label for=\"cgpa\">CGPA</label><br />\r\n");
      out.write("                            <input type=\"number\" id=\"cgpa\" name=\"cgpa\" min=0.0 max=10.0 step=0.01 required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </section>\r\n");
      out.write("                </fieldset>\r\n");
      out.write("                <fieldset name=\"company-details\" class=\"border-light pl-2 m-3\">\r\n");
      out.write("                    <legend>Company Questions</legend>\r\n");
      out.write("                    <section id=\"company-role\" class=\"row justify-content-between\">\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <label for=\"companybox\">Company</label><br />\r\n");
      out.write("                            <input type=\"text\" name=\"companybox\" id=\"companybox\" value=\"Selected company\" readonly required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <label for=\"role\">Role</label><br />\r\n");
      out.write("                            <select name=\"role\" id=\"role\" required>\r\n");
      out.write("                                <option value=\"SWE\">Software Engineer</option>\r\n");
      out.write("                                <option value=\"RD\">Research and Dev</option>\r\n");
      out.write("                                <option value=\"Sec\">System Security Engineer</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </section>\r\n");
      out.write("                    <section id=\"company-question\" class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <label for=\"question\">Answer the following</label><br />\r\n");
      out.write("                            <textarea id=\"question\" name=\"question\" minlength=50></textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </section>\r\n");
      out.write("                    <section id=\"resume-upload\" class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <label for=\"r-upload\">Upload your resume</label><br />\r\n");
      out.write("                            <input type=\"file\" id=\"r-upload\" name=\"r-upload\"/>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                </fieldset>\r\n");
      out.write("                <section class=\"container\" id=\"buttons\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <input type=\"reset\" class=\"btn btn-outline-info btn-block\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <input type=\"submit\" class=\"btn btn-outline-dark btn-block\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <section class=\"optional row\" id=\"company_link\">\r\n");
      out.write("        <div class=\"col text-center text-md-center\">\r\n");
      out.write("            <p>The company you have selected requires you to complete registration by going on its site at the\r\n");
      out.write("                link mentioned below.</p>\r\n");
      out.write("            \r\n");
      out.write("            <a href=\"http://amazon.com\">Complete registration</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function populate(selectedVal) {\r\n");
      out.write("            document.getElementById('companybox').value = selectedVal.value;\r\n");
      out.write("            console.log(selectedVal.value);\r\n");
      out.write("            if ((selectedVal.value)!='Amazon'){\r\n");
      out.write("                console.log('Here')\r\n");
      out.write("                document.getElementById(\"company_link\").style.visibility=\"hidden\";\r\n");
      out.write("            }\r\n");
      out.write("            else{\r\n");
      out.write("                document.getElementById(\"company_link\").style.visibility=\"visible\";\r\n");
      out.write("            }\r\n");
      out.write("           \r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
