/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.40
 * Generated at: 2020-12-06 21:55:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.sql.*;
import java.io.*;

public final class stage2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\"\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Company Details</title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS\\companydetails.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS\\navstyles.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS\\companylink.css\" />\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Exo+2:wght@300&family=Philosopher:wght@700&display=swap\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"navigationbar\" class=\"sticky-top\">\r\n");
      out.write("        <header class=\"row \">\r\n");
      out.write("            <div class=\"col-md-4 col-sm-12 my-auto\">\r\n");
      out.write("                <img src=\"Images\\amritalogo.png\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 col-sm-12 my-auto\">\r\n");
      out.write("                <h1>Student Portal</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 col-sm-12 my-auto\">\r\n");
      out.write("                <button type=\"button\" class=\"btn\" id=\"signinout\" value=\"logout\" name=\"signinout\">Logout</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <nav class=\"nav nav-pills nav-justified\">\r\n");
      out.write("            <a href=\"http://localhost:8080/mainpage.jsp\" class=\"nav-item nav-link\" target=\"mainframe\" id=\"home\"\r\n");
      out.write("                name=\"home\">Home</a>\r\n");
      out.write("            <a href=\"http://localhost:8080/companies_list.jsp\" class=\"nav-item nav-link\" id=\"companies\"\r\n");
      out.write("                name=\"companies\">Companies</a>\r\n");
      out.write("            <a href=\"http://localhost:8080/companyregistration.jsp\" class=\"nav-item nav-link \" id=\"register\"\r\n");
      out.write("                name=\"register\">Registration</a>\r\n");
      out.write("            <a href=\"http://localhost:8080/calendar.jsp\" class=\"nav-item nav-link\" id=\"calendar\"\r\n");
      out.write("                name=\"calendar\">Calendar</a>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"details_pagebody col text-center text-md-center\">\r\n");
      out.write("        <h1>Successful Submission - Page 2</h1>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

Connection con;
PreparedStatement ps1,ps2;
System.out.println("Entered Company Registration JSP");
try {
    Class.forName("com.mysql.cj.jdbc.Driver");
} catch (ClassNotFoundException e) {
    System.out.println("Class not found. " + e);
}
System.out.println("Class found");
try{
con = DriverManager.getConnection("jdbc:mysql://remotemysql.com:3306/6dO9xvYDBl", "6dO9xvYDBl", "uBQpS0PirH");
String query = "USE 6dO9xvYDBl";
Statement stmt = con.createStatement();
stmt.executeQuery(query);


String company = (String)session.getAttribute("registeredCompany");
System.out.println(company);

ps1 = con.prepareStatement("select CompanyLink from Companies where CompanyName = ?");
ps1.setString(1,company);
ResultSet rs = ps1.executeQuery();

String complink="link";

while (rs.next()){
    complink=rs.getString(1);
System.out.println("Link"+complink);
}
      out.write("\r\n");
      out.write("    <section class=\"optional row\" id=\"company_link\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col text-center text-md-center\">\r\n");
      out.write("            <p>The company you have selected requires you to complete registration by going on its site at the\r\n");
      out.write("                link mentioned below.</p>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"");
      out.print(complink);
      out.write("\" target=\"_blank\">Complete registration</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

ps1.close();
con.close();}
    catch(Exception e){
        System.out.println("Exception "+ e);
    }
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
